import next from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * Flat config, because `npm run lint` runs bare `eslint` and ESLint 9 looks for
 * exactly this file. Without it the script did not fail on a lint error — it
 * exited 2 before reading a single line of source, which is worse: a lint script
 * that cannot run is indistinguishable from a codebase with no lint problems.
 *
 * `core-web-vitals` is the stricter of the two Next presets (it promotes the
 * performance rules from warning to error), and the TypeScript preset adds the
 * parser and the TS-aware rules on top.
 */
const config = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Generated by scripts/build-search-index.mjs on every build.
      "public/search-index.json",
    ],
  },
  ...next,
  ...nextTypescript,
  {
    rules: {
      // Unused function arguments are how you document a signature you are
      // deliberately not using; unused *variables* are still an error.
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
];

export default config;
